erDiagram

    VENDOR_DATABASE {
        Integer vendor_id PK "Auto Increment, Unique, Not Null"
        Text vendor_name "Not Null"
        Integer contact_number "Unique"
        Text business_name "Not Null"
        Text locations "Not Null"
        Text nz_business "Not Null"
        Text handmade_nz "Not Null"
        Text designed_nz "Not Null"
        Text assembled_nz "Not Null"
    }